name: Environment Testing Workflow
on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'production' || 'development' }}
    steps:
      - name: Show Environment
        run: echo ${{ vars.TEST }}
