name: Environment Testing Workflow
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        default: "develop"
        type: choice
        options:
          - develop
          - staging
          - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || (github.ref_name == 'master' && 'production' || 'development') }}
    steps:
      - name: Show Environment
        run: |
          echo ${{ vars.TEST }}
          echo ${{ var.GITHUB_REPOSITORY }}
          echo $GITHUB_REPOSITORY
